let BTechCse = {
  semester1: {
    subject1: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject2: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject3: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject4: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject5: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
  },
  semester2: {
    subject1: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject2: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject3: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject4: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject5: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
  },
  semester3: {
    subject1: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject2: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject3: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject4: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject5: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
  },
  semester4: {
    subject1: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject2: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject3: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject4: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject5: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
  },
  semester5: {
    subject1: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject2: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject3: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject4: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject5: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
  },
  semester6: {
    subject1: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject2: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject3: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject4: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject5: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
  },
  semester7: {
    subject1: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject2: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject3: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject4: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject5: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
  },
  semester8: {
    subject1: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject2: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject3: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject4: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
    subject5: {
      chapter1: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter2: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter3: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter4: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
      chapter5: ["Topic 1", "Topic 2", "Topic 3", "Topic 4", "Topic 5"],
    },
  },
};